# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

n1 = int(input('Digite um número para obter sua tabuada: '))

print('A tabuada de adição do número {} é:'.format(n1))
print('{} + 0 = {}'.format(n1, n1+0))
print('{} + 1 = {}'.format(n1, n1+1))
print('{} + 2 = {}'.format(n1, n1+2))
print('{} + 3 = {}'.format(n1, n1+3))
print('{} + 4 = {}'.format(n1, n1+4))
print('{} + 5 = {}'.format(n1, n1+5))
print('{} + 6 = {}'.format(n1, n1+6))
print('{} + 7 = {}'.format(n1, n1+7))
print('{} + 8 = {}'.format(n1, n1+8))
print('{} + 9 = {}\n'.format(n1, n1+9))


print('A tabuada de subtração do número {} é:'.format(n1))
print('{} - 0 = {}'.format(n1, n1-0))
print('{} - 1 = {}'.format(n1, n1-1))
print('{} - 2 = {}'.format(n1, n1-2))
print('{} - 3 = {}'.format(n1, n1-3))
print('{} - 4 = {}'.format(n1, n1-4))
print('{} - 5 = {}'.format(n1, n1-5))
print('{} - 6 = {}'.format(n1, n1-6))
print('{} - 7 = {}'.format(n1, n1-7))
print('{} - 8 = {}'.format(n1, n1-8))
print('{} - 9 = {}\n'.format(n1, n1-9))


print('A tabuada de multiplicação do número {} é:'.format(n1))
print('{} * 0 = {}'.format(n1, n1*0))
print('{} * 1 = {}'.format(n1, n1*1))
print('{} * 2 = {}'.format(n1, n1*2))
print('{} * 3 = {}'.format(n1, n1*3))
print('{} * 4 = {}'.format(n1, n1*4))
print('{} * 5 = {}'.format(n1, n1*5))
print('{} * 6 = {}'.format(n1, n1*6))
print('{} * 7 = {}'.format(n1, n1*7))
print('{} * 8 = {}'.format(n1, n1*8))
print('{} * 9 = {}\n'.format(n1, n1*9))


print('A tabuada de divisão do número {} é:'.format(n1))
print('{} / 1 = {:.2f}'.format(n1, n1 / 1))
print('{} / 2 = {:.2f}'.format(n1, n1 / 2))
print('{} / 3 = {:.2f}'.format(n1, n1 / 3))
print('{} / 4 = {:.2f}'.format(n1, n1 / 4))
print('{} / 5 = {:.2f}'.format(n1, n1 / 5))
print('{} / 6 = {:.2f}'.format(n1, n1 / 6))
print('{} / 7 = {:.2f}'.format(n1, n1 / 7))
print('{} / 8 = {:.2f}'.format(n1, n1 / 8))
print('{} / 9 = {:.2f}'.format(n1, n1 / 9))