a = input('Digite algo! ')
print('O tipo primitivo desse valor é ', type(a))
print('Contém somente espaços? ', a.isspace())
print('É numérico? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúsculo? ', a.isupper())
print('Está em minúsculo ', a.islower())
print('Está capitalizado? ', a.istitle())
